---
title: "p8105_hw5_sl4660"
author: "Sibei Liu"
date: "2019/11/10"
output: github_document
---

```{r setup}
knitr::opts_chunk$set(set.seed(10))
```

# Problem 1
```{r,message=FALSE,warning=FALSE}
library(tidyverse)
library(ggrepel)


iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```



```{r}

fill_missing= function(x) {
  
  if (is.numeric(x)){
  replace_na(x,mean(x,na.rm=TRUE))
  } else if(is.character(x)){
    replace_na(x,"virginica")
  }    
}

iris_without_missing= iris_with_missing %>% 
  map(fill_missing) %>% 
  bind_cols() %>%  
  knitr::kable(digit=3)

iris_without_missing
```

The table after filling missing values is shown above

# Problem 2

```{r}
data_total=list.files("./data")
data_total=str_c("./data/",data_total)
```

```{r,message=FALSE,warning=FALSE}
data_total=list.files("./data") %>%
  tibble()  %>% 
  rename(file_name=".") %>% 
  mutate(
   detail= map(data_total,read_csv) 
  ) 

data_total
```


```{r,message=FALSE,warning=FALSE}
cleaned_data=data_total %>% 
separate(col=file_name,into=c("type","id"),sep="_")%>%
  mutate(id = gsub("\\.csv", "",id )) %>% 
  unnest() %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week_time",
    values_to = "data"
  ) 

cleaned_data
```


```{r}
ggplot(cleaned_data,aes(x=week_time,y=data,color=id,group=id))+geom_point()+geom_line()+facet_grid(~type)+theme(axis.text.x = element_text(angle = 60, hjust=1))
```

Comment: In control group, the lines are fluctuating.The data dosen't change a lot when time increases While in the experinment group, the genereal trend is upward. While the time increase, the data increases.

# Problem 3
when $\beta_1$=0
```{r}
sim_regression = function(n=30, beta0=2, beta1){
  
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, sd=sqrt(50))
  )
  
   lm(y ~ x, data = sim_data) %>% 
    broom:: tidy() %>% 
  filter(term=="x")  %>% 
  select(estimate,p.value) %>% 
  rename(beta1_hat="estimate") %>% 
  mutate(
    beta1_true=beta1
  ) 
}
output=rerun(10000,sim_regression(beta1=0)) %>% 
  bind_rows()

```
